version: '3.8'

services:
  flux-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - FLUX_OUTPUT_DIR=/tmp/flux_images
    volumes:
      - flux_images:/tmp/flux_images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  flux_images:
    driver: local